#!/bin/bash
sudo apt-get install python3-venv
sudo apt-get install git
git clone https://github.com/SteveArr/FlaskTutorialMicroblog.git microblog
cd microblog
python3 -m venv flask
cd flask/bin
source activate
pip install --upgrade pip
pip install flask
pip install flask-login
pip install flask-openid
pip install flask-mail
pip install flask-sqlalchemy
pip install sqlalchemy-migrate
pip install flask-whooshalchemy
pip install flask-wtf
pip install flask-babel
pip install guess_language
pip install flipflop
pip install coverage
#Download and install Visual Studio Code

